### ISSUE TITLE
No property models of calamancy

### ISSUE THREAD

**Issue by woodthom2** [ljvmiranda921/calamanCy#15]
Hi
I am trying to download the models but the `models` property doesn't exist, as described in the README

```
pip install --upgrade calamancy
Collecting calamancy
.........
Installing collected packages: calamancy
Successfully installed calamancy-0.0.1
```

Then in Python I cannot see an attribute `models` of calamancy
```
>>> for model in calamancy.models():
...     print(model)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'calamancy' has no attribute 'models'

>>> dir(calamancy)
['__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__']


```

**Comment by ljvmiranda921** [comment]
Hi @woodthom2 , I'm still working on the packages as I'm currently waiting for the treebank data from a uni here in the Philippines, so the packages still don't exist (hopefully by August!). Sorry I wasn't able to made that clear in the README. I'll ping you once everything's ready, and I appreciate your interest!

In the meantime, you can replicate the NER model as a spaCy project [here](https://github.com/ljvmiranda921/calamanCy/tree/master/datasets/tl_calamancy_gold_corpus). ([write-up](https://ljvmiranda921.github.io/notebook/2023/02/04/tagalog-pipeline/))

**Comment by ljvmiranda921** [comment]
Closing this for now! I have already trained the first few models but I want to run some few benchmarks first. I think we're still on track on the August promise.

**Comment by ljvmiranda921** [comment]
Hi @woodthom2 , the first few models have been released now. Feel free to update your calamanCy installation from `0.0.1` to `0.1.0`.

**Comment by woodthom2** [comment]
Thanks so much!
