### ISSUE TITLE
can't run it 

### ISSUE THREAD

**Issue by herbiel** [ljvmiranda921/calamanCy#18]
>>> import calamancy
>>> from model in calamancy.models():
  File "<stdin>", line 1
    from model in calamancy.models():
               ^^
SyntaxError: invalid syntax
>>>     print(model)
  File "<stdin>", line 1
    print(model)
IndentationError: unexpected indent
>>> import calamancy
>>> for model in calamancy.models():
...     print(model)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'calamancy' has no attribute 'models'
>>>

**Comment by ljvmiranda921** [comment]
Hi @herbiel , it's still work-in-progress but I'm hoping to have a proper release around August :) #15

**Comment by ljvmiranda921** [comment]
Hi @herbiel , the first few models have been released now. Feel free to update your calamanCy installation from `0.0.1` to `0.1.0`.
