### ISSUE TITLE
why not use  roberta-tagalog-large as context vectors

### ISSUE THREAD

**Issue by weixiu00** [ljvmiranda921/calamanCy#34]

**Comment by ljvmiranda921** [comment]
Mostly a compute issue, but currently working on it as I'm increasing my spending budget next year to make space for RoBERTa Tagalog (large), a decoder-only model, and seq2seq (encoder-decoder) model :)

**Comment by ljvmiranda921** [comment]
Closing this as we now have GliNER models that are more extensible
