### ISSUE TITLE
Download Error on tl-calamancy-lg

### ISSUE THREAD

**Issue by Tutuldot** [ljvmiranda921/calamanCy#35]
Hi,

Tried to use the model I encounter error on downloading  tl-calamancy-lg.

Below is the error message when I run nlp = calamancy.load("tl_calamancy_lg-0.1.0").

ERROR: HTTP error 404 while getting https://huggingface.co/ljvmiranda921/tl_calamancy_lg/resolve/55ef01a244f3ca77676de6ba5a2beea0ba3e0021/tl_calamancy_lg-any-py3-none-any.whl
ERROR: Could not install requirement tl-calamancy-lg==any from https://huggingface.co/ljvmiranda921/tl_calamancy_lg/resolve/55ef01a244f3ca77676de6ba5a2beea0ba3e0021/tl_calamancy_lg-any-py3-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://huggingface.co/ljvmiranda921/tl_calamancy_lg/resolve/55ef01a244f3ca77676de6ba5a2beea0ba3e0021/tl_calamancy_lg-any-py3-none-any.whl for URL [https://huggingface.co/ljvmiranda921/tl_calamancy_lg/resolve/55ef01a244f3ca77676de6ba5a2beea0ba3e0021/tl_calamancy_lg-any-py3-none-any.wh](https://huggingface.co/ljvmiranda921/tl_calamancy_lg/resolve/55ef01a244f3ca77676de6ba5a2beea0ba3e0021/tl_calamancy_lg-any-py3-none-any.whl)

Thank you.

Anthony

**Comment by ljvmiranda921** [comment]
Hi @Tutuldot ,

Can you try this? First install and download the model from HuggingFace:

```
pip install https://huggingface.co/ljvmiranda921/tl_calamancy_lg/resolve/main/tl_calamancy_lg-any-py3-none-any.whl
```

It's 450 MB file, so if the download errors out midway then it won't load fully. Then I suggest running this code:

```python
from calamancy.loaders import load
nlp = load("tl_calamancy_lg-0.1.0")
```

Alternatively, you can try:

```
import spacy
nlp = spacy.load("tl_calamancy_lg")
```

**Comment by Tutuldot** [comment]
thanks a lot. its now working. 




![image](https://github.com/ljvmiranda921/calamanCy/assets/11689399/435b55f6-e8fd-40eb-aa09-0d5bbf5eee71)
