### ISSUE TITLE
Can't install for Python 3.12?

### ISSUE THREAD

**Issue by lamrongol** [ljvmiranda921/calamanCy#43]
I tried to install by `pip install calamanCy` but following error occured.
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Successfully built spacy-transformers
Failed to build tokenizers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tokenizers)
```
I searched and similar error occurs for other tokenizer: [ERROR: Failed building wheel for tokenizers · Issue #1050 · huggingface/tokenizers](https://github.com/huggingface/tokenizers/issues/1050)

And, the solution is "Downgrading to python 3.10". For calamanCy, too, I succeeded installing and running on Python `3.10`.
This doesn't work on Python `3.12`?
Thanks,

**Comment by ljvmiranda921** [comment]
Closing this now
