### ISSUE TITLE
TLunified error upon downloading

### ISSUE THREAD

**Issue by andreo-serrano** [ljvmiranda921/calamanCy#44]
Good day!

I kindly request for your assistance on how can we resolve this issue when downloading the tlunified.zip because when I am trying to run "project assets" it does show that error and I am afraid that it will affect the further development that we want to implement?

        "✘ Download failed:
        /content/calamanCy/models/v0.1.0/assets/tlunified.zip
        403 Client Error: Forbidden for url:
        https://s3.us-east-2.amazonaws.com/blaisecruz.com/datasets/tlunified/tlunified.zip"

the link is not accessible and it shows like this:

        This XML file does not appear to have any style information associated with it. The document tree is shown below.
        <Error>
        <Code>InvalidObjectState</Code>
        <Message>The operation is not valid for the object's storage class</Message>
        <StorageClass>GLACIER</StorageClass>
        <RequestId>2WWKG9WS0B4W7EFA</RequestId>
        <HostId>qv1R6/iu8dTmCCeF71bVTSeALuIHWiaXRHZVefiQMR4NsaPVc7KaryFFyPSmthtXR+XaLeqOORQ2oawAqkhI5A==</HostId>
        </Error>

Hoping for your kindest response, thank you.

**Comment by ljvmiranda921** [comment]
Hi @andreo-serrano , yeah, turns out the original author has changed the link for this dataset and it's no longer accessible. I actually encountered this error early this week. 

Luckily, I kept a backup! Instead you can use this link:

```
  - dest: "assets/tlunified_raw_text.txt"
    description: "Pre-converted raw text from TLUnified in JSONL format (1.1 GB)."
    url: "https://storage.googleapis.com/ljvmiranda/calamanCy/tlunified_raw_text.txt"
```

This will download the `.txt` file that the`tlunified.zip` contains.

**Comment by ljvmiranda921** [comment]
Will be pushing a fix in a few :)

**Comment by andreo-serrano** [comment]
Good day!

Thank you for resolving the issue I was experiencing. I greatly appreciate your assistance.

To share our vision, we aim to enhance the existing model by incorporating new entity types such as Culture, Time, and Event. This will allow for a more comprehensive analysis and assessment of Filipino Cultural Heritage.

Additionally, we plan to integrate the CIDOC-CRM standard to ensure accurate representation of entities, particularly in addressing cultural nuances. This implementation will help maintain consistency and precision in capturing complex cultural contexts.

Thank you once again for your support, and we look forward to any guidance or feedback you may have regarding this initiative.


Best regards,
Andreo Serrano

**Comment by ljvmiranda921** [comment]
Hi @andreo-serrano , this is awesome! Yeah, I think a version with improved entity types would be super helpful for the community. You can also use [TLUnified-NER](https://huggingface.co/datasets/ljvmiranda921/tlunified-ner) as reference. :) 

Let me know if the dataset / model's been published and if you need additional help 👍
